### ISSUE TITLE
Modify template inside the advanced tab

### ISSUE THREAD

**Issue by ignoxx** [TuringTW/PageNumberGoogleSlide#1]
Hi, thank you for this add-on!! It's really weird google does not provide an option to show the total number of pages.

Can you add some sort of template editor, so that I don't have to edit every single slide to just adjust the formating? It would be awesome!

Thank you again :)

**Comment by TuringTW** [comment]
Hi, 

Sorry for my late reply. You can add a "page number template" from the Advanced option.
In this way, you don't need to edit the style and format page by page.
Here's a [tutorial](https://www.youtube.com/watch?v=7aexkFaW5dQ) for this.

Thank you for using this Add-on. I though the only user will be myself! lol
